spring.application.name=tryplace
server.port=8023
spring.main.web-application-type=servlet

# BANCO DE DADOS - SUPABASE
spring.datasource.url=jdbc:postgresql://db.hjlmunocssjfcfihuotb.supabase.co:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres
spring.datasource.password=tryplaceSegredos20
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

# JWT
api.security.token.secret=${JWT_SECRET:minha-senha-secreta-123}

# LOGS
logging.level.org.springframework.security=DEBUG

# GOOGLE MAPS
google.maps.api.key=AIzaSyBjxlVtr6dRLOba29iY_iXRfvGnJPZZ7hg

# EMAIL
spring.mail.host=smtp-relay.sendinblue.com
spring.mail.port=587
spring.mail.username=a8d6c5001@smtp-brevo.com
spring.mail.password=xsmtpsib-c7fb6eca2f9e7d8500cdfe4d5b31fc521cbcac5060e3e4d8e7a8de1a7f4e02fc-a8mV5Ct7PFiLZxfJ
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=elpedrorenan08@gmail.com