spring.application.name=tryplace
server.port=8023
spring.datasource.url=jdbc:postgresql://db.hjlmunocssjfcfihuotb.supabase.co:5432/postgres?user=postgres&password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
api.security.token.secret=${JWT_SECRET:minha-senha-secreta-123}
logging.level.org.springframework.security=DEBUG
google.maps.api.key=${GOOGLE_MAPS_KEY}

spring.mail.host=smtp-relay.sendinblue.com
spring.mail.port=587
spring.mail.username=a8d6c5001@smtp-brevo.com
spring.mail.password=${BREVO_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=elpedrorenan08@gmail.com