spring.application.name=tryplace
server.port=8088
spring.datasource.url=${SERVER_URL}prepareThreshold=0
spring.datasource.username=${TRYPLACE_USERNAME}
spring.datasource.password=${TRYPLACE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
api.security.token.secret=${JWT_SECRET:minha-senha-secreta-123}
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=falses
google.maps.api.key=${GOOGLE_MAPS_API_KEY}
spring.mail.host=smtp-relay.sendinblue.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME_2}
spring.mail.password=${SMTP_PASSWORD_2}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=${EMAIL_REMETENTE}